### ISSUE TITLE
Can not send message via Node-Red

### ISSUE THREAD

**Issue by Osrx** [ioBroker/ioBroker.telegram#16]
Hello!

Possibly I found an bug.
When I try to insert something in response field from Node-red ioBroker node, nothing sends to Telegram.
But when I update this field manually message sends successfully.

Possible this happens because node-red sends messages "From: node-red.0" user and via interface I send it "From: admin.0".

Also I can successfully send messages via text2command plugin...

**Comment by LovelySunshine** [comment]
Did you used "telegram.0.communicate.response" for sending?
I just tested it i node-red and it works fine.

**Comment by Osrx** [comment]
Update of ioBroker resolve any issues.
My fault, sorry!
