### ISSUE TITLE
missing messageid of last send message

### ISSUE THREAD

**Issue by robdg80** [ioBroker/ioBroker.telegram#23]
The Datapoint "telegram.0.communicate.requestChatId" and "telegram.0.communicate.requestMessageId" has currently the chatID and the messageId of the last recived message.

In some cases I need the chatID and the messageID of the last send message. (in case If I wan't to update or delete the last message by the Bot.)

To Thus the [BotAPI](https://core.telegram.org/bots/api#sendmessage) return a [Message](https://core.telegram.org/bots/api#message) object, of a message was send On success. As part of this returned object is the message_id and the chat identifier.

Would it be possible to have two additional objects in the Telegram adapter which containes the message and the chat ID of the last send message?

As workaround I currently stores my own message ID, where I use the value of "telegram.0.communicate.requestMessageId" and add a 1 on every send message anbd reset this to the value of "telegram.0.communicate.requestMessageId" on reciving a new message. But that solution is not so good.

**Comment by Haba1234** [comment]
Hi! in the next version I'll try to add additional parameters :)

**Comment by Haba1234** [comment]
Please test
https://github.com/Haba1234/ioBroker.telegram

**Comment by robdg80** [comment]
I have installed 1.0.12 from https://github.com/Haba1234/ioBroker.telegram, but the two new states does not appear.
I also have send some messages.
When the states will be created?

**Comment by Haba1234** [comment]
1. Save Token
2. Delete instance Telegram
3. Install driver from githab
4. Add instance Telegram
4. Restore Settings

**Comment by robdg80** [comment]
Thank You, seems to working good!
