### ISSUE TITLE
sendPhoto als Buffer senden können

### ISSUE THREAD

**Issue by AlGu1** [ioBroker/ioBroker.telegram#25]
Hallo,

könnte bitte einer der Entwickler die Möglichkeit einbauen ein Photo auch wie in der API möglich als Buffer (Binary) zu senden. Dadurch muss man das Bild einer Kamera z.B. nicht erst auf der Festplatte zwischenspeichern und kann es direkt senden. Beispiel:

`var TelegramBot = require('node-telegram-bot-api');
var bot = new TelegramBot(token);

var requestSettings = {
    url: 'http://httpbin.org/image',
    encoding: null
};

request(requestSettings, function (error, response, buffer) {
    if (!error && response.statusCode == 200) {
        bot.sendPhoto(chatId, buffer)
    }
});`

Leider habe ich im Moment keiner Zeit einen Fork zu machen und dies selber einzubauen.

Danke und Gruß AlGu

**Comment by bondrogeen** [comment]
While in test mode.
Install with github   https://github.com/Haba1234/ioBroker.telegram

The path to the picture should be accurately indicated

sendTo ('telegram.0', {
     text: "http://moziru.com/images/gray-wolf-clipart-cartoon-15.png"    
});

**Comment by AlGu1** [comment]
Hi,
my cam has no "jpg|png|jpeg|bmp" extension in the URL. Can you add an option or any else for this case.

Thank you 
AlGu

**Comment by bondrogeen** [comment]
In the new version there will be such an opportunity:

var fs = require('fs');
sendTo('telegram.0',{   
      text:   {   
        bufer:fs.readFileSync('/iobroker/node_modules/iobroker/video.mp4'),   
        type:"video"  // photo, audio, document, sticker, video, voice    
        }
});

You can in JS process the data and transfer the file as a buffer.
Wait for the next update.

**Comment by Haba1234** [comment]
Please test
https://github.com/Haba1234/ioBroker.telegram

**Comment by AlGu1** [comment]
Greate Job,

works with:

```
function gSendPushMessageImage(adapter, nachricht, imageUrl) {
    var request = require('request');
    var settings = {
        url: imageUrl,
        encoding: null
    };
    request(settings, function (error, response, buffer) {
        if (!error && response.statusCode == 200) {
            sendTo(adapter,{ text: { buffer: buffer, type: "photo" }, caption: nachricht });
        }
    });
}
```
Thanks
AlGu
