### ISSUE TITLE
Change "I don't undestand" message

### ISSUE THREAD

**Issue by Dome2075** [ioBroker/ioBroker.telegram#35]
Hey, is it possible to implement the feature to change the  "I don't undestand" message?

thank you very much

**Comment by Apollon77** [comment]
Can you please provide more information about that?

**Comment by Haba1234** [comment]
This says the driver "Text to command"

**Comment by BasGo** [comment]
Should be closed, because this message is not part of telegram adapter: it comes from text2command adapter as soon as a command is unknown.
