### ISSUE TITLE
Error 409

### ISSUE THREAD

**Issue by Elexil** [ioBroker/ioBroker.telegram#38]
Hi, 

I installed the adapter yesterday. Everything is configured an works perfectly. Except of this error running down my log files (700 entries in 10 minutes).

![2018-03-19 09_25_48-iobroker admin](https://user-images.githubusercontent.com/37534416/37587214-f8ec66a4-2b5e-11e8-8dde-d0aa8c16ffa1.png)

Does anyone has an idea how to handle this?

Thanks in advance.
Elexil

**Comment by wendy2702** [comment]
Seems to be the same issue: https://forum.iobroker.net/viewtopic.php?f=30&t=12718

please stop telegram adapter, check with ``ps -ef|grep io´´ if an telegram prozess is running. If yes kill the prozeß and after that you can start your instance via Web panel again.

Reboot the server should solve the problem as well.
