### ISSUE TITLE
telegram adapter high load!

### ISSUE THREAD

**Issue by robig** [ioBroker/ioBroker.telegram#42]
Hi, after updating to latest iobroker 3, i'm getting _a log of errors logged_ from telegram adapter:

polling_error:ETELEGRAM, ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
--

I've a watchdog running, restarting iobroker when a load of 6 is reached on my raspi3.
This is now happening every day!

I'm runnign telegram adapter version 1.1.4, because with v1.2.0 i was not able to connect to the bot at all!
should I try to update again?
Or make a remove/reinstall of the adapter?

**Comment by Apollon77** [comment]
Please check that only one process rsi running from telegram adapter!!

**Comment by robig** [comment]
Problem solved. Thanks
