### ISSUE TITLE
Automatischer Neustart

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.telegram#43]
Seit 3 Tagen startet der Telegram Adapter um 05:04 Uhr jeweils neu. In der Log steht "Scheduled Restart" bzw. Fehler Code 156.

**Comment by BuZZy1337** [comment]
Kannst du in den Instanz-Einstellungen im ioBroker deaktivieren.

Am 27. März 2018 05:11:43 schrieb "Tobias S." <notifications@github.com>:
Seit 3 Tagen startet der Telegram Adapter um 05:04 Uhr jeweils neu. In der 
Log steht "Scheduled Restart" bzw. Fehler Code 156.
