### ISSUE TITLE
Blocky "username" translates to user instead of chatID

### ISSUE THREAD

**Issue by ramizh** [ioBroker/ioBroker.telegram#44]
I am not sure if this is intended or if user has a function at all, but shouldn't "username" be the chatId so we can ad a text field to Username in blocky in order to text a specific person?
So far this only works when we use chatId: 'XXX' instead of user in JS.
Thanks in advance!

**Comment by BuZZy1337** [comment]
Username is username, chatID is chatID..
ChatID and Username are linked together.. I'm not sure what exactly you 
mean with that..?
It is possible to send a message to a specific user by using the Username 
or the ChatID..

**Comment by ramizh** [comment]
for example if I put in block the username 123456789 it will be like this in written code, but it wont send anything to anyone, most importantly nothing to the user specified.
`
sendTo("telegram.0", "send", {
        text: 'Test Message',
        user: '123456789'
    });
`

But if i change user with chatId then it will send the message to that specific user
`
sendTo("telegram.0", "send", {
        text: 'Test Message',
        chatId: '123456789'
    });
`

**Comment by BuZZy1337** [comment]
By the way.. If that issue is regarding blocky you should open an issue at https://github.com/ioBroker/ioBroker.javascript

**Comment by BuZZy1337** [comment]
Username has to be the username. Not the ChatID!

Check the data point telegram.0.communicate.users there is a list of chatID and the linked username.

**Comment by BuZZy1337** [comment]
Here is how my datapoint is looking like..
`{"40452xxxx":"BuZZy","41648xxxx":"otherUser"}`

So my telegram username is BuZZy and the chatID is 40452xxxx.

**Comment by ramizh** [comment]
okay before I used the whole thing with the ID and that is why it did not work. So in your case if you put BuZZy as username in blocky it will text you directly.
Is the username unique? Cause I have not chosen any and it basically used my first name to as username, so I am wondering if the user is not unique wouldn't it be more accurate to use the ID? Unless I missed a step where I set my first name as my username (doubt though)
Ill submit this again in iobroker.javascript if users are not unique.
Thanks for the help, much appreciated!

**Comment by ramizh** [comment]
Never mind, sometimes my brain is blocked completely. I just checked the app, I can set a username for myself now and it is unique, but if you never set one the adapter will use your first name as username!
My bad!

**Comment by BuZZy1337** [comment]
Well.. The Telegram Adapter picked my firstname as Uername too.. But i changed it to "BuZZy" in the example that i posted above..
Not sure if it picks the "public username" that you can set in the telegram app on your phone..
I connected the bot to my telegram app before i entered a public username in the telegram app.. :smiley:

**Comment by BuZZy1337** [comment]
P.s.: don't forget to close this issue here on github.. ;)

**Comment by ramizh** [comment]
I did not forget xD, I was testing he username thing and it does not work... Adapter assumes first name is the username. Even after I deleted everything and reinstalled and setup a bot again.
With chatId it is still far more reliable and reacts all the time, when using username (with my first name) to send a message to a specific person it sometimes for some reason does not send the message until a 2nd or 3rd trial.
So second problem is that the adapter takes first name as username instead of actual username.

**Comment by ramizh** [comment]
Issue moved to iobroker.javascript

**Comment by BuZZy1337** [comment]
Uhhmm.. Yeah, but now the issue is clearly related to telegram... So you should close the issue on the Javascript repo and reopen this one here! Haha.. Sorry about that.

**Comment by BuZZy1337** [comment]
Or better: open a new issue here in the telegram repo which describes the "new problem" that you have now.
