### ISSUE TITLE
New Line

### ISSUE THREAD

**Issue by Psens666** [ioBroker/ioBroker.telegram#46]
Hello,

how could i make a new line in a message response?

**Comment by BuZZy1337** [comment]
Use `\n` for new line in the message.

**Comment by Apollon77** [comment]
when you try "hello \\n world"

**Comment by BuZZy1337** [comment]
As mentioned above i just tested it with `\n` and it works..

`sendTo('telegram.0', {user: 'BuZZy1337', text: 'Test\nTest'});`

![screenshot 01 04 2018 11_14_40](https://user-images.githubusercontent.com/6979405/38171643-5943db38-359e-11e8-98bf-bdb524b7d697.png)

**Comment by dontobi** [comment]
\ n only works with JavaScript. with blockly that does not work.

**Comment by GermanBluefox** [comment]
Diese Anmerkung über Blockly ist SEHR wichtig

вс, 1 апр. 2018 г., 12:33 Tobias S. <notifications@github.com>:

**Comment by BuZZy1337** [comment]
https://forum.iobroker.net/viewtopic.php?f=21&t=4012&start=60#p141709

Eventuell hilft das?

**Comment by BuZZy1337** [comment]
Closed with solution:
Use https://forum.iobroker.net/viewtopic.php?f=21&t=4012&start=60#p141709 to generate Text containing Newline in Blockly.
