### ISSUE TITLE
Add please socks5 proxy support

### ISSUE THREAD

**Issue by 2scorpio** [ioBroker/ioBroker.telegram#50]
Add please tcp socks5 proxy support.
In Russia Telegram was blocked :(
It is very strongly necessary.

**Comment by Osrx** [comment]
Home Bot stop functioning today...
Russia....

Please add socks proxy support!

**Comment by Osrx** [comment]
Next text I found in following link:

https://github.com/yagop/node-telegram-bot-api/issues/562 <https://github.com/yagop/node-telegram-bot-api/issues/562>

Will it helps?

Where can we add proxy in iOBroker?




I quickly looked through code, and found that all API interactions rely on request-promise package, which supports connection through proxy

var request = require('request-promise').defaults({
    proxy:'http://username:password@host:port',
    strictSSL :false
  });


—
С уважением, Хабров Андрей.
Тел.: +7 (903) 728-2539

**Comment by GermanBluefox** [comment]
It is interesting. Thank you

вт, 17 апр. 2018 г., 10:43 Osrx <notifications@github.com>:

> Next text I found in following link:
>
> https://github.com/yagop/node-telegram-bot-api/issues/562 <
> https://github.com/yagop/node-telegram-bot-api/issues/562>
>
> Will it helps?
>
> Where can we add proxy in iOBroker?
>
>
>
>
> I quickly looked through code, and found that all API interactions rely on
> request-promise package, which supports connection through proxy
>
> var request = require('request-promise').defaults({
> proxy:'http://username:password@host:port',
> strictSSL :false
> });
>
>
> —
> С уважением, Хабров Андрей.
> Тел.: +7 (903) 728-2539
>
>
>

**Comment by Osrx** [comment]
Also there is a way to implement SOCK5 support to Telegram bot.
Can you add this in your connector?

https://github.com/yagop/node-telegram-bot-api/issues/562#issuecomment-382313307

**Comment by Haba1234** [comment]
Hi!

please test socks5 https://github.com/Haba1234/ioBroker.telegram

**Comment by Haba1234** [comment]
after installation with the github, you need to click "plus" (install the driver) on the tab "Drivers"

**Comment by Osrx** [comment]
Ok.
If I click "+" adapter installs. But in adapter settings I've see nothing about proxy... =(

There is two files index.html and index_m.html and only in second there is something about Proxy.
If I rename one to another I start to see settings page with proxy settings but there is no Save button...

Where is a problem?

**Comment by Haba1234** [comment]
Андрей, админка у тебя второй версии что-ли? Драйвер я апгрейдил под третью админку только (index_m.html который). В группе телеграм есть?

**Comment by Osrx** [comment]
Написано 2.0.9
Ума не приложу как ее обновить. Он не говорит что есть более новая версия я и не обновляю... =(
Ты про какую группу? Название дай.
мой контакт @Andrey_Khabrov

**Comment by kirovilya** [comment]
С прокси сейчас работает только отправка текста, а картинки и видео не отправляются.
Нашел упоминание этой же ошибки в используемой библиотеке https://github.com/mattcg/socks5-https-client/issues/22 но решения нет.

**Comment by Apollon77** [comment]
SHould be done since v1.2.2/1.2.3 ?! Please reopen if not
