### ISSUE TITLE
Fehler/Hinweis nach Update auf 1.2.4

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.telegram#57]
Nach Update auf telegram Version 1.2.4  bekomme ich folgenden Fehler/Hinweis im Log mit verweis auf [https://github.com/yagop/node-telegram-bot-api/issues/319](https://github.com/yagop/node-telegram-bot-api/issues/319)

```
Caught | 2018-06-03 22:05:05.724 | error | by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:577:32
Caught | 2018-06-03 22:05:05.724 | error | by controller[0]: In the future, you will have to enable it yourself.
Caught | 2018-06-03 22:05:05.724 | error | by controller[0]: Sun, 03 Jun 2018 20:04:53 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
```

**Comment by Apollon77** [comment]
Bitte ausführlicheres Log posten ... ist das alles?

**Comment by Hypnos3** [comment]
Der "Fehler" kam nur einmal im Log.
node -v = v6.12.2
nodejs -v = v6.14.1

**Comment by Apollon77** [comment]
Kommt er beim restart vom Adapter auch. 

Side note: irgendwie hast du zwei verschiedene nodejs Versionen ... solltest du fixen

**Comment by BuZZy1337** [comment]
Den "Fehler" (ist ja eigentlich eher ein Hinweis) hatte ich auch, ist für uns aber eher irrelevant weil der ioBroker Telegram Adapter kein Promise benutzt.

Beim Neustart des Adapters erscheint der Hinweis nicht.

**Comment by BuZZy1337** [comment]
Denke dies kann geschlossen werden, weil es uns nicht betrifft.
