### ISSUE TITLE
error: telegram.0 polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.telegram#60]
I receive the following error during the night for around 10 times in the row - anything i can do?
2018-07-04 03:17:02.725 - error: telegram.0 polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway

**Comment by BuZZy1337** [comment]
This is a server error from telegram. Not from the adapter. :relaxed:
