### ISSUE TITLE
Add possibility to send message to more than one User, but not to all!

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.telegram#61]
We have 10 registered users, but only want to send a message to user 1, 3 and 4..

sendTo telegram.0 user: 'User1,User3,User4' ...

**Comment by Hypnos3** [comment]
Internally the send to all loops through users and send them to all. So you can do the same in your code.

**Comment by BuZZy1337** [comment]
I know, for me it is not a problem at all.. But think about the users which don't have "good" Javascript knowledge.. ;)

**Comment by BuZZy1337** [comment]
Done with https://github.com/ioBroker/ioBroker.telegram/commit/c0670fdd6632a1f28b95637e4d4e6c3dcd7e95f8
