### ISSUE TITLE
At 5 o'clock am telegram is terminating

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.telegram#63]
I have to iobroker servers set up. On each of those servers I am receiving the following error message
`

host.raspberrypi | 2018-07-26 05:04:00.611 | info | Restart adapter system.adapter.telegram.0 because enabled
host.raspberrypi | 2018-07-26 05:04:00.610 | error | instance system.adapter.telegram.0 terminated with code 156 ()
telegram.0 | 2018-07-26 04:36:04.092 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 04:36:00.840 | error | polling_error:ETELEGRAM, ETELEGRAM: 500 Internal server error: restart
telegram.0 | 2018-07-26 04:21:44.415 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway

`
This occuring on both machine every day at the same time.

**Comment by Apollon77** [comment]
The bad gateway error (different time!!) means that the telegram servers are offline. Happens from time to time. 

Restart at 5am is default config. We had people that had problems with their daily internet reconnection. Can be changed in ioBroker Admin when you do not need the restart.
