### ISSUE TITLE
ETELEGRAM, ETELEGRAM: 502 Bad Gateway

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.telegram#64]
seit den letzten zwei updates bekomme ich immer Fehlermeldungen:

telegram.0 | 2018-07-26 03:14:23.329 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
-- | -- | -- | --
telegram.0 | 2018-07-26 03:14:23.006 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:22.684 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:22.360 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:22.037 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:21.715 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:21.391 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:21.067 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:20.743 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:20.419 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:14:20.093 | error | polling_error:ETELEGRAM, ETELEGRAM: 502 Bad Gateway
telegram.0 | 2018-07-26 03:04:02.336 | info | getMe (reconnect): {"id":3782233634,"is_bot":true,"first_name":"IoBroker","username":"ww_bot"}

**Comment by Apollon77** [comment]
Bitte an telegram wenden. Der Fehler heißt das deren Server weg ist.
