### ISSUE TITLE
Possibility to disable special commands (state)

### ISSUE THREAD

**Issue by klaus-schuster** [ioBroker/ioBroker.telegram#72]
it would be nice, if the state command could be disabled in the config tabs.
not every registered user should be able to read or change all states.

thanks for your work!

**Comment by BuZZy1337** [comment]
Implemented by @GermanBluefox 

With https://github.com/ioBroker/ioBroker.telegram/commit/f80ef9362daf143d1c89476af29ff164ff3a5bcd
