### ISSUE TITLE
unable to take Blockly  Adapter into Script

### ISSUE THREAD

**Issue by joeflower** [ioBroker/ioBroker.telegram#73]
When i try to include "send To" telegram into my Script, it always close after clicking on it.
I see the Script Adapter Icon, but when i click on it, it always close again.
More people with the same Problem here:
https://forum.iobroker.net/viewtopic.php?t=11377
last two entries.

**Comment by BuZZy1337** [comment]
You have installed either the sayit or the cloud adapter without creating an instance for it..

The solution is here:
https://forum.iobroker.net/viewtopic.php?p=187853#p178524
