### ISSUE TITLE
Adapter reboot when receiving message

### ISSUE THREAD

**Issue by nemec1234** [ioBroker/ioBroker.telegram#78]
The adapter is configured in "server" mode. If I send a message to the bot, the adapter reloads with an error. Messages from the adapter come to me without any problems.

| time | debug | message |
| --- | --- | --- |
| 2018-11-30 19:41:44.140 | - error: | telegram.0 uncaught exception: msg is not defined |
| 2018-11-30 19:41:44.141 | - error: | telegram.0 ReferenceError: msg is not defined |
| --- | --- | at IncomingMessage.req.on.e (/opt/iobroker/node_modules/iobroker.telegram/main.js:216:31) |
| --- | --- | at emitNone (events.js:86:13) |
| --- | --- | at IncomingMessage.emit (events.js:185:7) |
| --- | --- | at endReadableNT (_stream_readable.js:978:12) |
| --- | --- | at _combinedTickCallback (internal/process/next_tick.js:80:11) |
| --- | --- | at process._tickCallback (internal/process/next_tick.js:104:9) |
| 2018-11-30 19:41:44.646 | - info: | telegram.0 terminating |
| 2018-11-30 19:41:44.663 | - error: | Caught by controller[1]: ReferenceError: msg is not defined |
| 2018-11-30 19:41:44.665 | - error: | Caught by controller[1]: at IncomingMessage.req.on.e (/opt/iobroker/node_modules/iobroker.telegram/main.js:216:31) |
| 2018-11-30 19:41:44.665 | - error: | Caught by controller[1]: at emitNone (events.js:86:13) |
| 2018-11-30 19:41:44.665 | - error: | Caught by controller[1]: at IncomingMessage.emit (events.js:185:7) |
| 2018-11-30 19:41:44.665 | - error: | Caught by controller[1]: at endReadableNT (_stream_readable.js:978:12) |
| 2018-11-30 19:41:44.665 | - error: | Caught by controller[1]: at _combinedTickCallback (internal/process/next_tick.js:80:11) |
| 2018-11-30 19:41:44.665 | - error: | Caught by controller[1]: at process._tickCallback (internal/process/next_tick.js:104:9) |
| 2018-11-30 19:41:44.665 | - error: | host.iobroker instance system.adapter.telegram.0 terminated with code 0 (OK) |
| 2018-11-30 19:41:44.666 | - info: | host.iobroker Restart adapter system.adapter.telegram.0 because enabled |
| 2018-11-30 19:41:45.705 | - info: | host.iobroker instance system.adapter.telegram.0 started with pid 17078 |
| 2018-11-30 19:41:46.788 | - info: | telegram.0 starting. Version 1.3.5 in /opt/iobroker/node_modules/iobroker.telegram, node: v6.14.4 |
| 2018-11-30 19:41:48.440 | - info: | telegram.0 https server listening on port 8443 |

**Comment by Apollon77** [comment]
Please check 1.3.6 from Github and give feedback

**Comment by nemec1234** [comment]
Thank you, it works.

**Comment by Zefau** [comment]
Ich bekomme das Update nicht hin, liegt es an mir? 

> Update telegram from @1.3.5 to @1.3.6
> NPM version: 6.4.1
> npm install iobroker.telegram@1.3.6 --production --save --prefix "/opt/iobroker" (System call)
> Killed
> host.ioBroker-RasPi Cannot install iobroker.telegram@1.3.6: 137
> root@ioBroker-RasPi:/home/pi# iobroker url https://github.com/ioBroker/ioBroker.telegram
> install https://github.com/ioBroker/ioBroker.telegram/tarball/master
> npm install https://github.com/ioBroker/ioBroker.telegram/tarball/master --production --save --prefix "/opt/iobroker" (System call)
> Killed
> host.ioBroker-RasPi Cannot install https://github.com/ioBroker/ioBroker.telegram/tarball/master: 137

**Comment by Apollon77** [comment]
System call killed ... Speicher voll? Mal bitte reboot
