### ISSUE TITLE
Restart message in silent mode optionally

### ISSUE THREAD

**Issue by Pix---** [ioBroker/ioBroker.telegram#81]
As the adapter restarts after each iobroker restart (initiated by backitup or manually) or on every day (adapter cron) the push message "Bot wird neu gestartet" gets more and more annoying. I suggest an option in the adapter settings to activate silent mode (like in backitup).

**Comment by BuZZy1337** [comment]
You can delete the start and stop message in the settings of the telegram instance if you don't need it..?

**Comment by Pix---** [comment]
Thank you. I did not know this option. I should check the improvements after updating an adapter.
