### ISSUE TITLE
Automatic enabling of cancellation of promises is deprecated

### ISSUE THREAD

**Issue by DanielWeeber** [ioBroker/ioBroker.telegram#83]
`2019-01-08 20:14:21.303 - error: Caught by controller[0]: Tue, 08 Jan 2019 19:14:07 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.`
`2019-01-08 20:14:21.304 - error: Caught by controller[0]: In the future, you will have to enable it yourself.`
`2019-01-08 20:14:21.304 - error: Caught by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:653:30`
`2019-01-08 20:14:21.304 - info: host.iobroker instance system.adapter.telegram.1 terminated with code 0 (OK)`

**Comment by BuZZy1337** [comment]
This is not relevant for us. It is just a warning from the node-telegram-bot-API module.
But thank you for reporting. :relaxed:
