### ISSUE TITLE
Fehlermeldung im Log

### ISSUE THREAD

**Issue by indiBit** [ioBroker/ioBroker.telegram#86]
Beim täglichen Neustart des Adapters wird eine Meldung vom Typ error in die Logdatei geschrieben.
Da dieser Neustart des Adapters jedoch fest einprogrammiert ist und es sich dabei um ein normales Ereignis handelt, wäre es sehr wünschenswert, wenn die Meldung lediglich eine info-Meldung wäre.

**Comment by BuZZy1337** [comment]
Ahhh okay.. Wie apollon77 im Forum geschrieben hatte - bitte das issue im js-controller aufmachen:
https://github.com/ioBroker/ioBroker.js-controller

Hier im Telegram Adapter ist der falsche Ort dafür. :relaxed:

Gruß
