### ISSUE TITLE
Info getMe (reconnect) jede Stunde

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.telegram#87]
Ist es wichtig jede Stunden diesen Eintrag als Info zu bekommen?

telegram.0 | 2019-01-23 20:04:06.582 | info | getMe (reconnect):id":1124567890"is_bot":true,"first_name":.....

**Comment by BuZZy1337** [comment]
Ich nehme es auf meine Liste auf. :relaxed:
