### ISSUE TITLE
Keine Einstellungsmöglichkeit 

### ISSUE THREAD

**Issue by MubiTec** [ioBroker/ioBroker.telegram#92]
Version 1.43
Bei den Einstellungen eines Datenpunkts gibt es keine Einstellungsmöglichkeit für telegram. Der History Adapter z. B. ist allerdings zu sehen.
Browsercache wurde bereits gelöscht. 
Admin version 3.6 und 3.5.10 ausprobiert. Npm6.41 node 8.15

**Comment by Apollon77** [comment]
Bitte mal ein

iobroker upload telegram

Versuchen.

**Comment by MubiTec** [comment]
Ok, danke! Jetzt gehts!
